[tool.bumpversion]
current_version = "0.0.2"
message = "Bump version of package/qdrant-client-custom: {current_version} → {new_version}"
commit = false
tag = false
tag_name = "packages/qdrant-client-custom-v{new_version}"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(\\.(?P<dev>dev\\d+)\\+(?P<branch>.*))?"
serialize = ["{major}.{minor}.{patch}.{dev}+{branch}", "{major}.{minor}.{patch}"]

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""