[project]
name = "qdrant-client-custom"
version = "0.0.2"
description = ""
authors = [
    {name = "ruthuwjwb",email = "ruthuwjwb@gmail.com"}
]
readme = "README.md"
dependencies = [
    "qdrant-client (>=1.13.0,<2.0.0)",
]

[tool.poetry]
packages = [{include = "*", from="src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
