# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        files: \.(yaml|yml)$
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
        files: \.py$
      - id: trailing-whitespace
        files: \.py$
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
 
      - id: ruff-format
        files: \.py$

 
  # Run the test suite via Poetry as part of pre-commit
  - repo: local
    hooks:
      - id: pytest
        name: pytest (unit subset)
        entry: poetry run pytest tests/ -k "not integration" -v --lf
        language: system
        pass_filenames: false
        stages: [pre-commit]
