line-length = 88
target-version = "py310"

[lint]
select = ["ALL"]
ignore = [
    "BLE001",
    "F821",
    "PERF",
    "INP001",
    "A001",
    "PLW2901",
    "G",
    "E501",
    "PTH",
    "TRY",
    "ARG",
    "C",
    "ERA",
    "PLR",
    "DTZ",
    "S",
    "RUF",
    "PERF203",
    "ANN",
    "TRY401",
    "EM",
    "FBT",
    "TRY003",
    "D1",
    "D203",
    "D213",
    "G004",
    "FA",
    "COM812",
    "ISC001",
    "RUF001",
    "B904",
    "ASYNC230",
    "FIX002",
    "T",
    "T201",
    "T203",
    "SLF001",
    "PGH003",
    "F401",
    "N806",
    "N803",
    "N815",
    "N812",
    "N818",
    "PD901",
    "D400",
    "D401",
    "D405",
    "D415",
    "D417",
    "D205",
    "UP035",
    "UP008",
    "LOG015",
    "SIM102",
    "SIM105",
    "SIM117",
    "RET504",
    "B006",
    "B018",
    "E101",
    "E741",
    "TC002",
    "TC003",
    "PYI063",
    "A002",
    "F841",
    "TD002",
    "TD003",
    "TD004",
]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
