agent:
  name: praxis-python-agent
  version: 1.0.0
  description: Praxis P2P Agent with Python Implementation
  url: http://localhost:8000
  shared_dir: shared
  tools: []
  external_mcp_endpoints: []
  external_mcp_servers: []
  capabilities:
  - file_operations
  - python_execution
  - llm_integration
  max_concurrent_tasks: 10
  task_timeout: 300
p2p:
  enabled: true
  port: 4001
  host: 0.0.0.0
  rendezvous: praxis-agents
  enable_mdns: true
  enable_dht: true
  enable_relay: false
  bootstrap_nodes: []
  security:
    enabled: true
    noise_enabled: true
    authorized_peers: []
    blacklisted_peers: []
    max_peer_connections: 100
  connection_timeout: 30
  discovery_interval: 60
  protocol_version: 0.3.0
http:
  enabled: true
  port: 8000
  host: 0.0.0.0
  cors_origins:
  - http://localhost:3000
  - http://localhost:3001
  max_connections: 1000
  request_timeout: 30
  keepalive_timeout: 5
websocket:
  enabled: true
  port: 8090
  host: 0.0.0.0
  path: /ws/workflow
  ping_interval: 30
  ping_timeout: 10
  max_connections: 100
  message_size_limit: 1048576
mcp:
  enabled: true
  servers: []
  limits:
    max_concurrent_requests: 100
    request_timeout_ms: 30000
    max_response_size_bytes: 10485760
    max_servers_per_node: 10
    connection_pool_size: 5
    retry_attempts: 3
    retry_backoff_ms: 1000
  log_level: info
  discovery_enabled: true
  discovery_endpoints: []
  auto_register_tools: true
llm:
  enabled: true
  provider: openai
  model: gpt-4o-mini
  max_tokens: 4096
  temperature: 0.1
  timeout: 30
  function_calling:
    strict_mode: true
    max_parallel_calls: 5
    tool_timeout: 15
    retry_failed_calls: true
    max_retries: 2
  caching:
    enabled: true
    ttl: 300
    max_size: 1000
    cache_embeddings: true
  rate_limiting:
    requests_per_minute: 60
    tokens_per_minute: 100000
    burst_limit: 10
  always_use_llm_for_dsl: true
execution:
  default_engine: dagger
  dagger:
    enabled: true
    session_timeout: 300
    default_image: python:3.11-slim
    mount_docker_socket: true
    resource_limits:
      cpu: 1000m
      memory: 512Mi
  enable_sandboxing: true
  max_execution_time: 600
  cleanup_temp_files: true
logging:
  level: DEBUG
  format: text
  max_file_size: 100MB
  backup_count: 5
  enable_console: true
  enable_file: false
  structured_logging: false
  log_requests: false
  log_p2p_traffic: false
environment: development
debug: true
