[project]
name = "tik-tok-package"
version = "0.1.5"
description = "Tik tok video uploader"
authors = [
    {name = "hexavor",email = "bychynski.valiantsin@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "selenium (>=4.31.0,<5.0.0)",
    "tiktok-captcha-solver (>=0.7.5,<0.8.0)",
    "undetected-chromedriver (>=3.5.5,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
