# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
        files: \.(yaml|yml)$
    -   id: end-of-file-fixer
        files: \.py$
    -   id: trailing-whitespace
        files: \.py$
    -   id: check-merge-conflict
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: \.py$
    -   id: ruff-format
        files: \.py$

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: poetry run python scripts/run_mypy.py
        language: system
        types: [python]
        require_serial: true
        pass_filenames: false
