[project]
name = "example-package"
version = "0.0.6"
description = "This is an example package."
authors = [
    {name = "Your Name",email = "you@example.com"}
]
requires-python = ">=3.9"
dependencies = []
readme = "README.md"

[tool.setuptools.packages.find]
include = ['*']
where = ['src']

[build-system]
requires = ['setuptools>=61.0']
build-backend = "setuptools.build_meta"
