# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/shared/events/proto/schemas/news.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'services/shared/events/proto/schemas/news.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from services.shared.events.proto.schemas import meta_pb2 as services_dot_shared_dot_events_dot_proto_dot_schemas_dot_meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/services/shared/events/proto/schemas/news.proto\x12\x04news\x1a\x1fgoogle/protobuf/timestamp.proto\x1a/services/shared/events/proto/schemas/meta.proto\"\xb4\x01\n\x08NewsMeta\x12\x14\n\x07replies\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x12\n\x05views\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x16\n\treactions\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x33\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x03\x88\x01\x01\x42\n\n\x08_repliesB\x08\n\x06_viewsB\x0c\n\n_reactionsB\r\n\x0b_created_at\"\x96\x01\n\x04News\x12#\n\nevent_meta\x18\x01 \x01(\x0b\x32\x0f.meta.EventMeta\x12\x1c\n\x06source\x18\x02 \x01(\x0e\x32\x0c.news.Source\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x1c\n\x04meta\x18\x04 \x01(\x0b\x32\x0e.news.NewsMeta\x12\x0c\n\x04tags\x18\x05 \x03(\t\x12\x0e\n\x06\x61uthor\x18\x06 \x01(\t*.\n\x06Source\x12\t\n\x05OTHER\x10\x00\x12\x0c\n\x08TELEGRAM\x10\x01\x12\x0b\n\x07TWITTER\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.shared.events.proto.schemas.news_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SOURCE']._serialized_start=475
  _globals['_SOURCE']._serialized_end=521
  _globals['_NEWSMETA']._serialized_start=140
  _globals['_NEWSMETA']._serialized_end=320
  _globals['_NEWS']._serialized_start=323
  _globals['_NEWS']._serialized_end=473
# @@protoc_insertion_point(module_scope)
