apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    release: {{ .Values.prometheusRelease }}
  name: {{ include "agent.fullname" . }}-ray-worker-monitor
spec:
  jobLabel: {{ include "agent.fullname" . }}-ray-worker
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_label_ray_io_cluster
          targetLabel: ray_io_cluster
  selector:
    matchLabels:
      ray.io/node-type: worker
