[project]
name = "redis-utils"
version = "0.0.1"
description = "Package that consists redis-utils"
authors = [
    { name = "0xDevZip", email = "noreply@example.com" }
]
requires-python = ">=3.10,<4"
dependencies = [
    "asyncio>=3.4.3",
    "loguru>=0.7.2,<0.8.0",
    "redis-client==0.1.7",
    "pytest-asyncio (==0.26.0)",
    "pydantic_settings>=2.7.1",
]

readme = "README.md"



[tool.setuptools.packages.find]
include = ['*']
where = ['src']

[build-system]
requires = ['setuptools>=61.0']
build-backend = "setuptools.build_meta"
