[project]
name = "shared-clients"
version = "0.0.1"
description = "Package that consists shared clients"
authors = [
    { name = "0xDevZip", email = "noreply@example.com" }
]
requires-python = ">=3.10,<4"
dependencies = [
    "aiohttp>=3.11.14,<4.0.0",
    "msgspec>=0.19.0",
    "multidict>=6.4.4",
    "pydantic_settings>=2.7.1",
    "pytest-asyncio (==0.26.0)",
    "aioresponses==0.7.8"
]

readme = "README.md"

[tool.setuptools.packages.find]
include = ['*']
where = ['src']

[build-system]
requires = ['setuptools>=61.0']
build-backend = "setuptools.build_meta"
