[project]
name = "twitter-ambassador-utils"
version = "0.1.11"
description = "Package that consists utils for Twitter Ambassador"
authors = [
    {name = "0xDevZip",email = "noreply@example.com"}
]
requires-python = ">=3.10,<4"
dependencies = [
    "aiohttp (>=3.11.13)",
    "requests-oauthlib>=1.3.0",
    "cryptography (>=2.3.1)",
    "loguru==0.7.3",
    "hvac==2.3.0",
    "pydantic_settings>=2.7.1",
    "pytest-asyncio (==0.26.0)",
    "redis-client==0.1.7",
    "example-package",
]
readme = "README.md"



[tool.setuptools.packages.find]
include = ['*']
where = ['src']

[build-system]
requires = ['setuptools>=61.0']
build-backend = "setuptools.build_meta"
