[project]
name = "agents-tools-logger"
version = "0.0.1"
description = "Logger for agents and tools"
authors = [
    {name = "hexavor",email =  "bychynski.valiantsin@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "loguru (>=0.7.3,<0.8.0)"
]


[build-system]
requires = ['setuptools>=61.0']
build-backend = "setuptools.build_meta"


[tool.setuptools.packages.find]
include = ['*']
where = ['src']
