[project]
name = "tool-exception"
version = "0.0.1"
description = "Package that consists tool exceptions of Praxis project"
authors = [
    {name = "0xDevZip",email = "noreply@example.com"}
]
requires-python = ">=3.10,<4"
dependencies = []
readme = "README.md"

[tool.setuptools.packages.find]
include = ['*']
where = ['src']

[build-system]
requires = ['setuptools>=61.0']
build-backend = "setuptools.build_meta"
