name: Release - praxis-sdk-agents

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable.publish-agent.yml
    with:
      path: .
      agent_name: praxis-sdk-agents
    secrets:
      OCI_REGISTRY_TOKEN: ${{ secrets.OCI_REGISTRY_TOKEN }}
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
