[project]
name = "shared-events"
version = "0.0.1"
description = "Package that consists events"
authors = [
    { name = "0xDevZip", email = "noreply@example.com" }
]
requires-python = ">=3.10,<4"
dependencies = [
    "loguru>=0.7.2,<0.8.0",
    "pydantic>=2.6.4",
    "protobuf >=6.31.1",
]

readme = "README.md"

[tool.setuptools.packages.find]
include = ['*']
where = ['src']

[build-system]
requires = ['setuptools>=61.0']
build-backend = "setuptools.build_meta"
