[project]
name = "qdrant-client-custom"
version = "0.0.3"
description = ""
authors = [
    {name = "ruthuwjwb",email = "ruthuwjwb@gmail.com"}
]
requires-python = ">=3.10,<4"
readme = "README.md"
dependencies = [
    "qdrant-client (>=1.13.0,<2.0.0)",
    "pytest-asyncio (==0.26.0)",
    "pydantic_settings>=2.7.1",

]

[tool.setuptools.packages.find]
include = ['*']
where = ['src']

[build-system]
requires = ['setuptools>=61.0']
build-backend = "setuptools.build_meta"
