[project]
name = "example-package"
version = "0.0.5"
description = "This is an example package."
authors = [
    {name = "Your Name",email = "you@example.com"}
]
requires-python = ">=3.9"
dependencies = []
readme = "README.md"

[tool.poetry]
packages = [{include = "*", from="src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
