[project]
name = "dextools-wrapper"
version = "0.0.1"
description = "Wrapper for DexTools API"
authors = [
     {name = "hexavor",email = "bychynski.valiantsin@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10,<4"
dependencies = [
    "aiohttp (>=3.11.14,<4.0.0)",
    "aiolimiter (>=1.2.1)",
    "pytest-asyncio (==0.26.0)",
]

[tool.setuptools.packages.find]
include = ['*']
where = ['src']

[build-system]
requires = ['setuptools>=61.0']
build-backend = "setuptools.build_meta"
