[project]
name = "twitter-follow"
version = "0.0.1"
description = ""
authors = [
    {name = "bychynski.valiantsin@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp (>=3.11.13,<4.0.0)",
    "pytest-asyncio (==0.26.0)",
    "pydantic_settings>=2.7.1",
]


[build-system]
requires = ['setuptools>=61.0']
build-backend = "setuptools.build_meta"
