[tool.bumpversion]
current_version = "0.1.0"
message = "Bump version of praxis-sdk-agents: {current_version} → {new_version}"
commit = false
tag = false
tag_name = "v{new_version}"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "praxis_sdk/agents/card/config.py"
search = "version: str = \"{current_version}\""
replace  = "version: str = \"{new_version}\""
