[project]
name = "redis-client"
version = "0.1.2"
description = "Package that create Redis client"
authors = [
    {name = "0xDevZip",email = "noreply@example.com"}
]
requires-python = ">=3.10,<4"
dependencies = [
    "redis>=4.5.0",
]
readme = "README.md"

[tool.poetry]
packages = [{include = "*", from="src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
