[project]
name = "redis-client"
version = "0.1.7"
description = "Package that create Redis client"
authors = [
    {name = "0xDevZip",email = "noreply@example.com"}
]
requires-python = ">=3.10,<4"
dependencies = [
    "redis>=4.5.0",
    "pytest-asyncio (==0.26.0)",
    "pydantic_settings>=2.7.1",
]
readme = "README.md"

[tool.setuptools.packages.find]
include = ['*']
where = ['src']

[build-system]
requires = ['setuptools>=61.0']
build-backend = "setuptools.build_meta"
