name: Release - praxis-sdk-providers

on:
  workflow_dispatch:
    inputs:
      part:
        description: 'Part to bump (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install bump-my-version
        run: |
          pip install --upgrade pip
          pip install bump-my-version

      - name: Configure Git
        run: |
          git config --global user.name hyp0cr4t
          git config --global user.email "hyp0cr4t@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.RELEASE_TOKEN }}@github.com/${{ github.repository }}

      - name: Bump version and create tag
        run: |
          bump-my-version bump --tag --commit ${{ inputs.part }}
          git push --follow-tags
