apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    release: {{ .Values.prometheusRelease }}
  name: {{ include "base-agent.fullname" . }}-ray-head-monitor
spec:
  jobLabel: {{ include "base-agent.fullname" . }}-ray-head
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      relabelings:
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_label_ray_io_cluster
          targetLabel: ray_io_cluster
  selector:
    matchLabels:
      ray.io/node-type: head
