[project]
name = "rugcheck-wrapper"
version = "0.0.1"
description = "Wrapper for RugCheck API"
authors = [
     {name = "hexavor",email = "bychynski.valiantsin@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10,<4"
dependencies = [
    "aiohttp (>=3.11.14,<4.0.0)",
    "pydantic_settings>=2.7.1",
    "pytest-asyncio (==0.26.0)",
]


[build-system]
requires = ['setuptools>=61.0']
build-backend = "setuptools.build_meta"
