"""A2A (Agent-to-Agent) Protocol Models

Comprehensive Pydantic models implementing the A2A protocol specification
from https://a2a-protocol.org with full JSON-RPC 2.0 compliance.
"""

import time
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Union
from uuid import uuid4

from pydantic import BaseModel, Field, ValidationInfo, field_validator


class TaskState(str, Enum):
    """Task execution states according to A2A specification v0.3.0."""

    SUBMITTED = "submitted"
    WORKING = "working"
    COMPLETED = "completed"
    FAILED = "failed"
    INPUT_REQUIRED = "input-required"
    CANCELED = "canceled"
    REJECTED = "rejected"
    AUTH_REQUIRED = "auth-required"
    UNKNOWN = "unknown"


class MessageRole(str, Enum):
    """Message role types."""

    USER = "user"
    AGENT = "agent"


class PartKind(str, Enum):
    """Part content types."""

    TEXT = "text"
    FILE = "file"
    DATA = "data"


class A2AFile(BaseModel):
    """File attachment model."""

    name: str | None = None
    mime_type: str | None = Field(None, alias="mimeType")
    bytes: str | None = None  # base64 encoded
    uri: str | None = None

    model_config = {"populate_by_name": True}


class Part(BaseModel):
    """Smallest unit of content within a Message or Artifact."""

    kind: PartKind
    text: str | None = None
    file: A2AFile | None = None
    data: Any | None = None

    @field_validator("text")
    @classmethod
    def validate_text_part(cls, v, info: ValidationInfo):
        if info.data.get("kind") == PartKind.TEXT and not v:
            raise ValueError("Text parts must have text content")
        return v

    @field_validator("file")
    @classmethod
    def validate_file_part(cls, v, info: ValidationInfo):
        if info.data.get("kind") == PartKind.FILE and not v:
            raise ValueError("File parts must have file content")
        return v

    @field_validator("data")
    @classmethod
    def validate_data_part(cls, v, info: ValidationInfo):
        if info.data.get("kind") == PartKind.DATA and v is None:
            raise ValueError("Data parts must have data content")
        return v


class Message(BaseModel):
    """Communication turn between client and agent."""

    role: MessageRole
    parts: list[Part]
    message_id: str = Field(alias="messageId", default_factory=lambda: str(uuid4()))
    task_id: str | None = Field(None, alias="taskId")
    context_id: str | None = Field(None, alias="contextId")
    kind: Literal["message"] = Field(default="message")

    model_config = {"populate_by_name": True}


class TaskStatus(BaseModel):
    """Current state of a task."""

    state: TaskState
    message: Message | None = None
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat() + "Z")


class Artifact(BaseModel):
    """Output generated by the agent as a result of a task."""

    artifact_id: str = Field(alias="artifactId", default_factory=lambda: str(uuid4()))
    name: str | None = None
    description: str | None = None
    parts: list[Part]
    metadata: dict[str, Any] | None = None

    model_config = {"populate_by_name": True}


class Task(BaseModel):
    """Fundamental unit of work managed by A2A."""

    id: str = Field(default_factory=lambda: str(uuid4()))
    context_id: str = Field(alias="contextId", default_factory=lambda: str(uuid4()))
    status: TaskStatus
    history: list[Message] = Field(default_factory=list)
    artifacts: list[Artifact] = Field(default_factory=list)
    metadata: dict[str, Any] | None = None
    kind: Literal["task"] = Field(default="task")

    model_config = {"populate_by_name": True}


class RPCError(BaseModel):
    """JSON-RPC error object."""

    code: int
    message: str
    data: Any | None = None


class JSONRPCRequest(BaseModel):
    """JSON-RPC 2.0 request."""

    jsonrpc: Literal["2.0"] = Field(default="2.0")
    id: str | int
    method: str
    params: dict[str, Any] | None = None


class JSONRPCResponse(BaseModel):
    """JSON-RPC 2.0 response."""

    jsonrpc: Literal["2.0"] = Field(default="2.0")
    id: str | int
    result: Any | None = None
    error: RPCError | None = None

    @field_validator("error")
    @classmethod
    def validate_error_result_mutual_exclusion(cls, v, info: ValidationInfo):
        if v is not None and info.data.get("result") is not None:
            raise ValueError("Response cannot have both result and error")
        return v

    @field_validator("result")
    @classmethod
    def validate_result_error_mutual_exclusion(cls, v, info: ValidationInfo):
        if v is not None and info.data.get("error") is not None:
            raise ValueError("Response cannot have both result and error")
        return v


# A2A JSON-RPC Error Codes (matching Go SDK)
class A2AErrorCode:
    TASK_NOT_FOUND = -32001
    TASK_NOT_CANCELABLE = -32002
    INVALID_PARAMS = -32602
    METHOD_NOT_FOUND = -32601
    INTERNAL_ERROR = -32603
    PARSE_ERROR = -32700


# A2A Method Parameter Models


class MessageSendParams(BaseModel):
    """Parameters for message/send method."""

    message: Message


class TasksGetParams(BaseModel):
    """Parameters for tasks/get method."""

    id: str


class TasksListParams(BaseModel):
    """Parameters for tasks/list method."""

    state: TaskState | None = None
    limit: int | None = Field(default=100, ge=1, le=1000)
    offset: int | None = Field(default=0, ge=0)


class TasksCancelParams(BaseModel):
    """Parameters for tasks/cancel method."""

    id: str


# A2A Agent Card Models (Full Specification Compliance)


class A2ASkill(BaseModel):
    """Agent skill definition."""

    id: str
    name: str
    description: str
    tags: list[str] = Field(default_factory=list)


class A2ACapabilities(BaseModel):
    """Agent capabilities."""

    streaming: bool | None = None
    push_notifications: bool | None = Field(None, alias="pushNotifications")
    state_transition_history: bool | None = Field(None, alias="stateTransitionHistory")
    extensions: list[dict[str, Any]] | None = None

    model_config = {"populate_by_name": True}


class A2AProvider(BaseModel):
    """Agent provider information."""

    name: str
    version: str | None = None
    description: str | None = None
    url: str | None = None


class TransportProtocol(str, Enum):
    """Supported transport protocols for A2A interfaces."""

    JSONRPC = "JSONRPC"
    GRPC = "GRPC"
    HTTP_JSON = "HTTP+JSON"


class AgentInterface(BaseModel):
    """Mapping between a transport protocol and concrete URL."""

    url: str
    transport: TransportProtocol | str


class ERC8004Registration(BaseModel):
    """ERC-8004 registration record exposed in agent card."""

    agent_id: int | None = Field(None, alias="agentId")
    agent_address: str | None = Field(None, alias="agentAddress")
    signature: str | None
    registry: str | None = Field(None, alias="registry")


class A2AAgentCard(BaseModel):
    """Complete A2A agent card according to specification (v0.3.0)."""

    protocol_version: str = Field(alias="protocolVersion", default="0.3.0")
    name: str
    description: str
    url: str
    preferred_transport: TransportProtocol | str = Field(
        alias="preferredTransport", default=TransportProtocol.JSONRPC
    )
    capabilities: A2ACapabilities = Field(default_factory=A2ACapabilities)
    skills: list[A2ASkill] = Field(default_factory=list)
    default_input_modes: list[str] = Field(
        alias="defaultInputModes",
        default_factory=lambda: ["application/json", "text/plain"],
    )
    default_output_modes: list[str] = Field(
        alias="defaultOutputModes",
        default_factory=lambda: ["application/json", "text/plain"],
    )
    provider: A2AProvider | None = None
    security_schemes: dict[str, Any] | None = Field(None, alias="securitySchemes")
    security: list[dict[str, list[str]]] | None = None
    additional_interfaces: list[AgentInterface] | None = Field(
        None, alias="additionalInterfaces"
    )
    metadata: dict[str, Any] | None = None

    # Compatibility fields
    version: str | None = None
    supported_transports: list[str] | None = Field(None, alias="supportedTransports")
    supports_authenticated_extended_card: bool | None = Field(
        None, alias="supportsAuthenticatedExtendedCard"
    )
    registrations: list[ERC8004Registration] | None = None
    signatures: list[dict[str, Any]] | None = None

    model_config = {"populate_by_name": True}


# Helper Functions for Creating A2A Objects


def create_task(
    context_id: str | None = None, initial_message: Message | None = None
) -> Task:
    """Create a new task with default values."""
    task_id = str(uuid4())
    if context_id is None:
        context_id = str(uuid4())

    status = TaskStatus(state=TaskState.SUBMITTED)
    history = [initial_message] if initial_message else []

    # Update message with task and context IDs if provided
    if initial_message:
        initial_message.task_id = task_id
        initial_message.context_id = context_id

    return Task(id=task_id, context_id=context_id, status=status, history=history)


def create_message(
    role: MessageRole,
    parts: list[Part],
    message_id: str | None = None,
    task_id: str | None = None,
    context_id: str | None = None,
) -> Message:
    """Create a new message."""
    return Message(
        role=role,
        parts=parts,
        message_id=message_id or str(uuid4()),
        task_id=task_id,
        context_id=context_id,
    )


def create_text_part(text: str) -> Part:
    """Create a text part."""
    return Part(kind=PartKind.TEXT, text=text)


def create_file_part(file: A2AFile) -> Part:
    """Create a file part."""
    return Part(kind=PartKind.FILE, file=file)


def create_data_part(data: Any) -> Part:
    """Create a data part."""
    return Part(kind=PartKind.DATA, data=data)


def create_artifact(
    name: str,
    parts: list[Part],
    description: str | None = None,
    metadata: dict[str, Any] | None = None,
) -> Artifact:
    """Create a new artifact."""
    return Artifact(name=name, parts=parts, description=description, metadata=metadata)


def create_rpc_error(code: int, message: str, data: Any | None = None) -> RPCError:
    """Create a new RPC error."""
    return RPCError(code=code, message=message, data=data)


def create_jsonrpc_response(request_id: str | int, result: Any) -> JSONRPCResponse:
    """Create a successful JSON-RPC response."""
    return JSONRPCResponse(id=request_id, result=result)


def create_jsonrpc_error_response(
    request_id: str | int, error: RPCError
) -> JSONRPCResponse:
    """Create an error JSON-RPC response."""
    return JSONRPCResponse(id=request_id, error=error)


# Standard A2A agent capabilities
def create_default_capabilities() -> A2ACapabilities:
    """Create default agent capabilities."""
    return A2ACapabilities(
        streaming=True, push_notifications=True, state_transition_history=True
    )


# Standard A2A skills for Praxis agents
def create_praxis_skills() -> list[A2ASkill]:
    """Create standard Praxis agent skills."""
    return [
        A2ASkill(
            id="python-execution",
            name="Python Code Execution",
            description="Execute Python scripts and analyze data",
            tags=["python", "coding", "analysis"],
        ),
        A2ASkill(
            id="file-operations",
            name="File Operations",
            description="Read, write, and manipulate files in shared workspace",
            tags=["filesystem", "io"],
        ),
        A2ASkill(
            id="data-processing",
            name="Data Processing",
            description="Process and analyze data using various tools",
            tags=["data", "analysis"],
        ),
        A2ASkill(
            id="workflow-orchestration",
            name="Workflow Orchestration",
            description="Coordinate complex multi-step workflows across agents",
            tags=["orchestration", "workflow", "dsl"],
        ),
        A2ASkill(
            id="p2p-communication",
            name="P2P Communication",
            description="Communicate with other agents via P2P network",
            tags=["p2p", "networking", "collaboration"],
        ),
    ]


def create_skills_from_tools(tools: list) -> list[A2ASkill]:
    """Create A2A skills from configured tools."""
    skills = []

    # Map common tool names to skill categories
    tool_skill_mapping = {
        "write_file": "file-operations",
        "read_file": "file-operations",
        "list_files": "file-operations",
        "python_analyzer": "python-execution",
        "execute_python": "python-execution",
        "code_execution": "python-execution",
    }

    for tool in tools:
        tool_name = getattr(tool, "name", str(tool))
        tool_description = getattr(tool, "description", f"Tool: {tool_name}")

        # Determine skill category
        skill_id = tool_skill_mapping.get(tool_name, f"tool-{tool_name}")

        # Create appropriate tags based on tool name
        tags = ["tool"]
        if "file" in tool_name.lower():
            tags.extend(["filesystem", "io"])
        elif "python" in tool_name.lower() or "code" in tool_name.lower():
            tags.extend(["python", "execution", "analysis"])
        elif "data" in tool_name.lower():
            tags.extend(["data", "processing"])

        skills.append(
            A2ASkill(
                id=skill_id,
                name=tool_name.replace("_", " ").title(),
                description=tool_description,
                tags=tags,
            )
        )

    return skills


def create_dynamic_agent_card(
    name: str,
    description: str,
    url: str,
    tools: list | None = None,
    additional_skills: list[A2ASkill] | None = None,
    provider: A2AProvider | None = None,
) -> A2AAgentCard:
    """Create a dynamic A2A agent card based on available tools and configuration."""
    # Start with standard Praxis skills
    skills = create_praxis_skills()

    # Add skills from tools if provided
    if tools:
        tool_skills = create_skills_from_tools(tools)
        skills.extend(tool_skills)

    # Add any additional custom skills
    if additional_skills:
        skills.extend(additional_skills)

    # Remove duplicate skills by ID
    unique_skills = {}
    for skill in skills:
        if skill.id not in unique_skills:
            unique_skills[skill.id] = skill

    # Set default provider if not provided
    if not provider:
        provider = A2AProvider(
            name="Praxis",
            url="https://prxs.ai",
            description="Advanced AI agent framework with P2P networking and MCP integration",
        )

    card = A2AAgentCard(
        name=name,
        description=description,
        url=url,
        skills=list(unique_skills.values()),
        capabilities=create_default_capabilities(),
        provider=provider,
        supported_transports=[TransportProtocol.JSONRPC.value],
        additional_interfaces=[
            AgentInterface(url=url, transport=TransportProtocol.JSONRPC)
        ],
        supports_authenticated_extended_card=True,
    )

    return card
