[project]
name = "twitter-ambassador-utils"
version = "0.0.1"
description = "Package that consists utils for Twitter Ambassador"
authors = [
    {name = "0xDevZip",email = "noreply@example.com"}
]
requires-python = ">=3.10,<4"
dependencies = [
    "aiohttp (>=3.11.13)",
    "requests-oauthlib>=1.3.0",
    "cryptography (>=2.3.1)"
]
readme = "README.md"

[tool.poetry]
packages = [{include = "*", from="src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
