name: Packages - publish redis-client

on:
  push:
    branches-ignore:
      - "main"
      - "staging"
      - "hotfix/**"
      - "release/**"
    paths:
      - "packages/redis-client/**"
    tags:
      - "packages/redis-client-v*"

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable.publish-python.yml
    with:
      path: ./packages/redis-client
    secrets:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
