name: Packages - publish infra-configs

on:
  push:
    branches-ignore:
      - "main"
      - "staging"
      - "hotfix/**"
      - "release/**"
    paths:
      - "packages/infra-configs/**"
    tags:
      - "packages/infra-configs-v*"

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable.publish-python.yml
    with:
      path: ./packages/infra-configs
    secrets:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}