name: Packages - publish twitter-follow

on:
  push:
    branches-ignore:
      - "main"
      - "staging"
      - "hotfix/**"
      - "release/**"
    paths:
      - "packages/twitter-follow/**"
    tags:
      - "packages/twitter-follow-v*"

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable.publish-python.yml
    with:
      path: ./packages/twitter-follow
    secrets:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
