name: Packages - publish example-package

on:
  push:
    branches-ignore:
      - "main"
      - "staging"
      - "hotfix/**"
      - "release/**"
    paths:
      - "packages/example-package/**"
    tags:
      - "packages/example-package-v*"

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable.publish-python.yml
    with:
      path: ./packages/example-package
    secrets:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
