name: Packages - publish tweetscout-utils

on:
  push:
    branches-ignore:
      - "main"
      - "staging"
      - "hotfix/**"
      - "release/**"
    paths:
      - "packages/tweetscout-utils/**"
    tags:
      - "packages/tweetscout-utils-v*"

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable.publish-python.yml
    with:
      path: ./packages/tweetscout-utils
    secrets:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}