name: Pre-commit checks

on:
  push:
    branches-ignore:
      - "main"
      - "staging"
      - "hotfix/**"
      - "release/**"
    paths:
      - "packages/**"
      - ".pre-commit-config.yaml"
      - "pyproject.toml"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "packages/**"
      - ".pre-commit-config.yaml"
      - "pyproject.toml"

jobs:
  pre-commit:
    name: Run Pre-commit checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Cache pre-commit hooks
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install dependencies
        run: poetry install --with dev --no-root

      - name: Run pre-commit
        run: poetry run pre-commit run --all-files --show-diff-on-failure
