name: Reusable - Python Publish to CodeArtifact

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

env:
  POETRY_REPOSITORIES_PRX_URL: https://packages.pypi.prx.ai/simple/
  POETRY_HTTP_BASIC_PRX_USERNAME: prx

jobs:
  build:
    defaults:
      run:
        working-directory: ${{ inputs.path }}
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install deps
      run: |
        pip install poetry bump-my-version

    - name: Set branch version
      if: ${{ github.ref_type == 'branch' }}
      run: |
        VERSION=$(bump-my-version show current_version)
        # Replace both slashes and dots with hyphens to ensure a valid version string
        BRANCH=$(echo ${GITHUB_REF_NAME} | sed 's/[\/\.]/-/g' | awk '{print tolower($0)}')
        # Get short commit hash
        COMMIT_HASH=$(git rev-parse --short HEAD)
        echo "VERSION=$VERSION.dev0+$BRANCH.$COMMIT_HASH" >> $GITHUB_ENV
        bump-my-version bump --new-version "$VERSION.dev0+$BRANCH.$COMMIT_HASH" branch

    - name: Publish to registry
      run: |
        poetry publish --build -r prx
      env:
        POETRY_HTTP_BASIC_PRX_PASSWORD: ${{ secrets.REGISTRY_TOKEN }}