[project]
name = "tweetscout-utils"
version = "0.0.4"
description = "Package that consists utils for Tweetscout"
authors = [
    {name = "0xDevZip",email = "noreply@example.com"}
]
requires-python = ">=3.10,<4"
dependencies = [
    "aiohttp (>=3.11.13)",
    "tenacity (>=8.1.0,!=8.4.0,<10)",
    "asyncio (>=3.4.3)",
    "pydantic_settings>=2.7.1",
    "pytest-asyncio (==0.26.0)",
]
readme = "README.md"

[tool.setuptools.packages.find]
include = ['*']
where = ['src']

[build-system]
requires = ['setuptools>=61.0']
build-backend = "setuptools.build_meta"
