[project]
name = "dexcreener-wrapper"
version = "0.0.1"
description = "Wrapper for DexScreener API."
authors = [
     {name = "hexavor",email = "bychynski.valiantsin@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp (>=3.11.14,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
