[project]
name = "tweetscout-utils"
version = "0.0.2"
description = "Package that consists utils for Tweetscout"
authors = [
    {name = "0xDevZip",email = "noreply@example.com"}
]
requires-python = ">=3.10,<4"
dependencies = [
    "aiohttp (>=3.11.13)",
    "tenacity (>=8.1.0,!=8.4.0,<10)",
    "asyncio (>=3.4.3)"
]
readme = "README.md"

[tool.poetry]
packages = [{include = "*", from="src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
