[project]
name = "ai-tools"
version = "0.0.1"
description = "Package that consists ai tools"
authors = [
    { name = "0xDevZip", email = "noreply@example.com" }
]
requires-python = ">=3.10,<4"
dependencies = [
    "loguru>=0.7.2,<0.8.0",
    "openai (>=1.63.2,<2.0.0)",
    "aiohttp (>=3.11.13)",
    "tenacity (>=8.1.0,!=8.4.0,<10)",
    "asyncio (>=3.4.3)",
    "pytest-asyncio (==0.26.0)",
    "send-openai-request (==0.1.2)",
    "pydantic_settings>=2.7.1",
    "infra-configs (==0.0.3)",

]

readme = "README.md"



[tool.setuptools.packages.find]
include = ['*']
where = ['src']

[build-system]
requires = ['setuptools>=61.0']
build-backend = "setuptools.build_meta"
